[package]
name = "test2"
version = "0.1.0"
edition = "2021"

[dependencies]
pcap = "0.10"
pnet = "0.34"
twox-hash = "1.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sysinfo = "0.21.1"
procfs = "0.11.0"
rand = "0.8"